apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastapi-storage-service-pv
  namespace: fastapi-storage-service
  labels:
    app: storage-service
spec:
  capacity:
    storage: 64Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kub-fastapi-storage-service-pv
