apiVersion: v1
kind: Service
metadata:
  name: fastapi-storage-service-service
  namespace: fastapi-storage-service
  labels:
    app: storage-service
spec:
  type: NodePort
  selector:
    app: storage-service-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31001